# Generated by Django 5.1.3 on 2024-11-22 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='api.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='General Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='308 Negra Arroyo Lane'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='Not provided', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(default='Not provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
