   services:
     - type: web
       name: illumine-backend
       env: python
       rootDir: backend
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn backend.wsgi:application
       envVars:
         - key: DJANGO_SECRET_KEY
           generateValue: true
         - key: DJANGO_DEBUG
           value: "False"

   databases:
     - name: illumine-db
       databaseName: illumine
       user: illumine_user